version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - "C:\\ProgramData\\Docker\\volumes\\b2w-desafio_dbdata"
    ports:
      - 27017:27017
volumes:
  b2w-desafio_dbdata: